special command case

diff --git a/chang b/chang
--- a/chang
+++ b/chang
@@ -28,21 +28,26 @@ done
 
 cmd=${1:-}
 
+run() {
+  if [[ ! -x $1 ]]; then
+    echo "$1 is not executable" >&2
+    exit 1
+  fi
+  $1 "${@:2}"
+}
+
 if [[ ${cmd_dir}/${cmd} != ".chang/bin/" ]]; then
   if [[ -z $cmd ]]; then
-    ${cmd_dir}
-  elif [[ -f ${cmd_dir}/$cmd ]]; then
-    if [[ ! -x ${cmd_dir}/$cmd ]]; then
-      echo "${cmd_dir}/$cmd is not executable" >&2
+    if [[ -f "${cmd_dir}/${cmd_dir##*/}" ]]; then
+      run "${cmd_dir}/${cmd_dir##*/}"
+    else
+      echo "command not found" >&2
       exit 1
     fi
-    ${cmd_dir}/$cmd "${@:2}"
-  elif [[ -f ${cmd_dir}/${cmd_dir##*/} ]]; then
-    if [[ ! -x ${cmd_dir}/${cmd_dir##*/} ]]; then
-      echo "${cmd_dir}/$cmd is not executable" >&2
-      exit 1
-    fi
-    ${cmd_dir}/${cmd_dir##*/} "${@:1}"
+  elif [[ -f "${cmd_dir}/${cmd}" ]]; then
+    run "${cmd_dir}/${cmd}" "${@:2}"
+  elif [[ -f "${cmd_dir}/${cmd_dir##*/}" ]]; then
+    run "${cmd_dir}/${cmd_dir##*/}" "${@:1}"
   else
     echo "command not found" >&2
     exit 1
